reports:
  exclude_paths:
    - contracts/testing/*.*

networks:
  development:
    cmd_settings:
      accounts: 100
      chain_id: 1337
  mainnet-fork:
    host: https://mainnet.infura.io/v3/56f22f6f02894d55809f1dcbc0f65bd9
    cmd_settings:
      unlock: 0xC447FcAF1dEf19A583F97b3620627BF69c05b5fB

autofetch_sources: True
dependencies:
  - curvefi/curve-crypto-contract@1.0.0
